---
- name: reload bird
  systemd:
    name: bird
    state: reloaded

- name: reload bird6
  systemd:
    name: bird6
    state: reloaded

- name: reread systemd configs
  systemd:
    daemon_reload: yes

- name: rebuilt v4 prefixes
  shell: /etc/bird/bird.conf.d/bgpq3-update-prefixes.sh

- name: rebuilt v6 prefixes
  shell: /etc/bird/bird6.conf.d/bgpq3-update-prefixes.sh
