- name: IPv4-Paketweiterleitung aktivieren
  sysctl: name="net.ipv4.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-ip_forwarding.conf

- name: IPv6-Paketweiterleitung aktivieren
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-ip_forwarding.conf

- name: sysctl Reverse-Path-Filter default deaktivieren - Quellroute nicht prüfen
  sysctl: name="net.ipv4.conf.default.rp_filter" value=0 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-ip_forwarding.conf

- name: sysctl Reverse-Path-Filter all deaktivieren - Quellroute nicht prüfen
  sysctl: name="net.ipv4.conf.all.rp_filter" value=0 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-ip_forwarding.conf

- name: sysctl ARP-Flux verhindern 1
  sysctl: name="net.ipv4.conf.all.arp_announce" value=1 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-arp_flux.conf

- name: sysctl ARP-Flux verhindern 2
  sysctl: name="net.ipv4.conf.all.arp_ignore" value=2 sysctl_set=yes state=present reload=yes sysctl_file=/etc/sysctl.d/ff-arp_flux.conf
