- name: install nginx
  apt:
    pkg: ['nginx']
    update_cache: yes
    state: latest

- name: create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: Install default nginx site for letsencrypt requests and https rewrite
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
  register: gendefconf

- name: Activate default nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  register: actdefconf

- name: Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted
  when: gendefconf.changed or actdefconf.changed

- name: acme install
  shell: wget -O -  https://get.acme.sh | sh
  args:
    creates: /root/.acme.sh/acme.sh

- name: Create certificate
  shell: /root/.acme.sh/acme.sh --server letsencrypt --issue -d {{inventory_hostname_short}}.{{freifunk.domain}} -w /var/www/letsencrypt
  args:
    creates: /root/.acme.sh/{{inventory_hostname_short}}.{{freifunk.domain}}/ca.cer

- name: install cert to Nginx
  shell: /root/.acme.sh/acme.sh --installcert -d {{inventory_hostname_short}}.{{freifunk.domain}} --keypath "/etc/ssl/key.pem" --fullchainpath "/etc/ssl/fullchain.pem" --reloadcmd "systemctl restart nginx"
  args:
    creates: /etc/ssl/certs/key.pem
  
- name: Generate dhparams
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: Install default ssl nginx site
  template:
    src: templates/default_ssl.j2
    dest: /etc/nginx/sites-available/default_ssl
  notify:
    - restart nginx

- name: Aktivate default ssl nginx site
  file:
    src: /etc/nginx/sites-available/default_ssl
    dest: /etc/nginx/sites-enabled/default_ssl
    state: link
  register: actsslconf

- name: Reload nginx to activate letsencrypt site
  service:
    name: nginx
    state: restarted
  when: actsslconf.changed
