- name: Extract yanic.tar into /usr/local/bin
  unarchive:
    src: yanic.tar
    dest: /usr/local/bin

- name: Changing perm of yanic binary
  file: dest=/usr/local/bin/yanic mode=u=rwX,g=rX,o=rX

- name: Deploy respondd service
  copy: src=respondd.service dest=/lib/systemd/system/respondd.service

- name: Deploy respondd.conf
  template:
    src: respondd.conf.j2
    dest: /etc/respondd.conf
  notify: restart respondd
  when: domaenenliste is defined

- name: Enable service respondd
  service:
    name: respondd
    enabled: yes

- name: Start service respondd
  service:
    name: respondd
    state: started


